---
 - name: Ansible client playbook
   hosts: client
   become: true
   tasks:
    - name: Update and upgrade apt packages
      apt:
            upgrade: yes
            update_cache: yes

    - name: Ansible install git
      apt:
            name: git
            state: latest

    - name: Install lynx
      apt:
        name: lynx
        state: latest
...
