---
 - name: Ansible client playbook
   hosts: client
   become: true
   tasks:
    - name: Update and upgrade apt packages
      apt:
            upgrade: yes
            update_cache: yes

    - name: Ansible install git
      apt:
            name: git
            state: latest

    - name: Ansible install wireshark
      apt:
            name: wireshark-qt
            state: latest

    - name: Ansible install tshark
      apt:
            name: tshark
            state: latest

    #- name: Ansible initialize tshark
    #  ansible.builtin.shell: tshark -i "eth1" --autostop duration:30 -w "/vagrant/ansible/captura.pcapng" &

    - name: Ansible expect telnet connection
      expect:
            command: telnet "10.10.10.11"
            responses:
                    server login: "vagrant"
                    Password: "vagrant"
                    vagrant@server(.*): "exit"
      ignore_errors: true
...
