---
 - name: Ansible server playbook
   hosts: server
   become: true
   tasks:
    - name: Update and upgrade apt packages
      apt:
            upgrade: no
            update_cache: yes
        
    - name: Install pip
      become: true
      ansible.builtin.apt:
            name: python3-pip
            state: latest

    - name: Install passlib
      become: true
      ansible.builtin.apt:
            name: python3-passlib

    - name: Ansible install git
      apt:
            name: git
            state: latest

    - name: loadkeys es
      command: loadkeys es

    - name: Modify /etc/vconsole.conf with KEYMAP=es
      lineinfile:
        path: /etc/vconsole.conf
        regexp: '^KEYMAP='
        line: 'KEYMAP="es"'
        create: true

    - name: Modify /etc/vconsole.conf with XKBLAYOUT=es
      lineinfile:
        path: /etc/vconsole.conf
        regexp: '^XKBLAYOUT='
        line: 'XKBLAYOUT="es"'
        create: true

    - name: create user usuarioServidor
      user:
            name: usuarioServidor
            shell: /bin/bash
            create_home: yes
            state: present
            groups: sudo
            password: "{{ 'servidor' | password_hash('sha512') }}"
...
