---
 - name: Ansible server playbook
   hosts: server
   become: true
   tasks:
    #- name: Update and upgrade apt packages
    #  apt:
    #        upgrade: yes
    #        update_cache: yes

    - name: Ansible install git
      apt:
            name: git
            state: latest

    - name: Ansible install wireshark
      apt:
            name: wireshark
            state: latest

    - name: Install pip
      become: true
      ansible.builtin.apt:
            name: python3-pip
            state: latest

    - name: Install passlib
      become: true
      ansible.builtin.apt:
            name: python3-passlib

    - name: create user usuarioServidor
      user:
            name: usuarioServidor
            shell: /bin/bash
            create_home: yes
            state: present
            groups: sudo
            password: "{{ 'servidor' | password_hash('sha512') }}"
...
