---
 - name: Ansible client playbook
   hosts: client
   become: true
   tasks:
    #- name: Update and upgrade apt packages
    #  apt:
    #        upgrade: yes
    #        update_cache: yes

    - name: Ansible install git
      apt:
            name: git
            state: latest

    - name: set spanish as locale
      locale_gen:
            name: es_ES
            state: present

    - name: set spanish as default locale
      command: localectl set-locale LANG=es_ES.UTF-8

    - name: set as default x11-keymap Ubuntu
      command: localectl set-keymap es
        

    - name: create user usuarioCliente
      user:
            name: usuarioCliente
            shell: /bin/bash
            create_home: yes
            state: present
            groups: sudo
            password: "{{ 'cliente' | password_hash('sha512') }}"

    - name: create user otroCliente
      user:
            name: otroCliente
            shell: /bin/bash
            create_home: yes
            state: present
            groups: sudo
            password: "{{ 'otro' | password_hash('sha512') }}"
...
